import { requireStaffPage } from "@/lib/staff-access";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { DEFAULT_ORG_ID } from "@/lib/constants";
import { getOwnedPackage, packageProgress, scopeContentSchema } from "@/lib/work-package";
import { addWorkStepEvidence, recordWorkStepReview, uploadWorkPackageEvidence } from "@/app/actions";
import { PageHeader } from "@/components/page-header";
import { Panel, Button } from "@/components/ui";
import { money } from "@/lib/format";

export default async function WorkPackagePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string>> }) {
  await requireStaffPage();
  const actor = await requireStaffPage(), { id } = await params, work = await getOwnedPackage(prisma, id);
  const query = await searchParams;
  const scope = scopeContentSchema.parse(work.scopeItem.content), progress = packageProgress(work), complete = progress.every(value => value.done);
  const files = await prisma.fileAsset.findMany({ where: { organizationId: DEFAULT_ORG_ID, entityType: "JOB", entityId: work.scopeItem.jobId, storageProvider: "private-volume" }, orderBy: { createdAt: "desc" } });
  const field = "mt-1 w-full rounded-md border border-border bg-white px-3 py-2";
  return <><PageHeader title={scope.title} body={`${work.scopeItem.job.jobName} · ${work.phase.phaseName} · ${scope.area}`} /><Link className="mb-4 inline-block text-primary underline" href={`/jobs/${work.scopeItem.jobId}/work-packages`}>← Job work packages</Link>
    {query.error && <p role="alert" className="mb-4 rounded border border-amber-300 bg-amber-50 p-3 text-sm">{query.error}</p>}
    <Panel className="mb-5 p-5"><h2 className="font-semibold">{complete ? "Required evidence and human reviews complete" : "Work remains open"}</h2><p className="mt-2 text-sm">{progress.filter(value => value.done).length} of {progress.length} steps accepted. {scope.quantity} {scope.unit} · allocated contract value {money(work.scopeItem.amount)}. Generation alone is not permission to start or cover work.</p><p className="mt-2 text-sm">Installer: {scope.installerName}. Flipside owner remains accountable for QC. Actual trade and authority requirements: {scope.authorityRequirements}</p><p className="mt-2 whitespace-pre-wrap text-sm">Included: {scope.inclusions}</p><p className="mt-2 whitespace-pre-wrap text-sm">Excluded: {scope.exclusions}</p><p className="mt-2 whitespace-pre-wrap text-sm">Measurements and products: {scope.measurementNotes}</p><p className="mt-2 text-sm">Installer competence: {scope.installerQualifications}</p><div className="mt-3 flex flex-wrap gap-4 text-sm"><a className="text-primary underline" href={`/api/files/${work.scopeItem.sourceFileId}`}>Accepted-scope source</a><Link className="text-primary underline" href={`/service-templates/work-items/${work.scopeItem.workItemVersionId}`}>Retained work version</Link><Link className="text-primary underline" href={`/cost-intelligence/${work.scopeItem.priceSnapshotId}`}>Retained price</Link></div></Panel>
    <Panel className="mb-5 p-5"><h2 className="font-semibold">Retain original evidence files</h2><p className="mt-2 text-sm">Upload a photo or PDF, then select it under the actual step and explain what it proves. Uploading alone does not satisfy a requirement.</p><form action={uploadWorkPackageEvidence.bind(null,id)} className="mt-3 flex flex-wrap gap-3"><input type="file" name="file" accept="image/jpeg,image/png,image/webp,application/pdf" required aria-label="Original evidence file" /><Button type="submit">Retain private file</Button></form></Panel>
    <div className="grid gap-5">{progress.map(current => <Panel key={current.step.id} className="p-5"><h2 className="font-semibold">{current.step.position + 1}. {current.definition.title}</h2><p className="mt-1 text-xs font-semibold">{current.state.replaceAll('_',' ')}{current.definition.holdPoint ? ' · HOLD POINT' : ''}</p><p className="mt-3 text-sm">{current.definition.instructions}</p>{current.definition.condition && <p className="mt-2 text-sm">Conditional branch: {current.definition.condition}</p>}
      <ul className="my-3 space-y-1 text-sm">{current.definition.evidence.map(item => <li key={item.key}>{item.label} · {item.kind.toLowerCase()} · {current.step.evidence.some(value => value.requirementKey === item.key) ? 'record submitted; review required' : 'missing'}</li>)}</ul>
      {current.step.evidence.map(evidence => <div key={evidence.id} className="my-2 rounded border border-border p-3 text-sm"><p className="font-semibold">{current.definition.evidence.find(item => item.key === evidence.requirementKey)?.label}</p><p className="whitespace-pre-wrap">{evidence.notes}</p><p className="mt-1 text-xs">Recorded by {evidence.submittedByName} · {evidence.createdAt.toISOString()}</p>{evidence.sourceFileId && <a href={`/api/files/${evidence.sourceFileId}`} className="text-primary underline">Open retained file</a>}</div>)}
      {current.priorReady && !current.done && <form action={addWorkStepEvidence.bind(null,id,current.step.id)} className="mt-4 grid gap-3"><input type="hidden" name="requestId" value={randomUUID()} /><label className="text-sm">Evidence requirement<select name="requirementKey" required className={field}>{current.definition.evidence.filter(item => item.kind !== 'REVIEW' || actor.role === 'OWNER').map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="text-sm">Observation, measurements, dates, result and responsible person<textarea name="notes" required minLength={20} maxLength={5000} rows={3} className={field} /></label><label className="text-sm">Private file (required for photo evidence)<select name="sourceFileId" className={field}><option value="">Written record only</option>{files.map(file => <option key={file.id} value={file.id}>{file.fileName} · {file.createdAt.toISOString().slice(0,10)}</option>)}</select></label><Button type="submit">Record step evidence</Button></form>}
      {!current.priorReady && <p className="mt-3 text-sm font-semibold">Prior steps must have current accepted reviews before this work proceeds.</p>}
      <form action={recordWorkStepReview.bind(null,id,current.step.id)} className="mt-4 grid gap-3 border-t border-border pt-4"><input type="hidden" name="requestId" value={randomUUID()} /><input type="hidden" name="reviewedDigest" value={current.reviewDigest} /><label className="text-sm">Human review outcome<select name="outcome" required defaultValue="BLOCKED" className={field}><option value="BLOCKED">Blocked / reopen: unresolved issue</option>{actor.role === 'OWNER' && current.priorReady && !current.done && <><option value="ACCEPTED">Accept evidence and release this step</option>{current.definition.condition && <option value="NOT_APPLICABLE">Conditional branch does not apply</option>}</>}</select></label><label className="text-sm">Review findings, issue resolution or actual N/A reason<textarea name="reason" required minLength={20} maxLength={5000} rows={3} className={field} /></label><p className="text-xs">Acceptance records your actual review of the evidence and applicable inspection requirements. Reopening an earlier step invalidates dependent reviews until they are reviewed again.</p><Button type="submit">Retain review decision</Button></form>
      {current.step.reviews.length > 0 && <details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">Retained review history</summary>{current.step.reviews.map(review => <div key={review.id} className="mt-2 border-l-2 border-border pl-3"><p>{review.outcome.replaceAll('_',' ')} · {review.reviewedByName} · {review.createdAt.toISOString()}</p><p className="whitespace-pre-wrap">{review.reason}</p></div>)}</details>}
    </Panel>)}</div></>;
}
