import { requireStaffPage } from "@/lib/staff-access";
import Link from "next/link";
import { ArrowUpRight, Search, Plus, ArrowRight } from "lucide-react";
import { StatusPill } from "@/components/status-pill";
import { dateShort, money } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { flipsideInvoiceWhere } from "@/lib/financial-record-scope";
import { austinDay, collectionViews, matchesCollectionView, summarizeCollections, type CollectionView } from "@/lib/invoice-collections";

const labels: Record<CollectionView,string> = { all:"All invoices", overdue:"Overdue", upcoming:"Due within 7 days", review:"Receipt review", drafts:"Drafts", paid:"Paid" };
export default async function InvoicesPage({ searchParams }: { searchParams: Promise<Record<string,string | string[] | undefined>> }) {
  await requireStaffPage();
  const query = await searchParams, q = (typeof query.q === "string" ? query.q : "").trim().slice(0,160);
  const view: CollectionView = collectionViews.includes(query.view as CollectionView) ? query.view as CollectionView : "all";
  const status = typeof query.status === "string" && ["DRAFT","SENT","PARTIALLY_PAID","PAID","OVERDUE","VOID"].includes(query.status) ? query.status : "";
  const invoices = await prisma.invoice.findMany({ where: flipsideInvoiceWhere, include: { job: {select:{id:true,jobName:true}}, clientProfile:{select:{profileName:true}}, payments:{select:{status:true,amount:true}} }, orderBy: [{issueDate:"desc"},{id:"asc"}] });
  const today = austinDay(), summary = summarizeCollections(invoices,today);
  const visible = summary.rows.filter(({invoice}) => matchesCollectionView(invoice,view,today) && (!status || invoice.status===status) && (!q || [invoice.invoiceNumber,invoice.clientProfile?.profileName,invoice.job?.jobName].some(value=>value?.toLowerCase().includes(q.toLowerCase()))));
  const href = (next: CollectionView) => "/invoices?"+new URLSearchParams({view:next,...(q?{q}:{})});
  return <div className="space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-6"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted-foreground">Flipside / Financial control</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Invoices &amp; collections</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Know what is owed, resolve receipt differences, and move each invoice forward.</p></div><Link href="/invoices/new" className="inline-flex items-center gap-2 rounded-md bg-foreground px-4 py-3 text-sm font-semibold text-background"><Plus size={16} aria-hidden="true"/>New invoice</Link></header>
    <section aria-label="Collections overview" className="grid grid-cols-2 border-y border-border bg-white lg:grid-cols-4">
      {[{label:"Recorded outstanding",value:money(summary.outstanding),note:"Issued invoices with a positive balance",to:"all"},{label:"Past due",value:money(summary.overdue),note:"Based on due dates, not saved status",to:"overdue"},{label:"Due within 7 days",value:money(summary.upcoming),note:"Includes invoices due today",to:"upcoming"},{label:"Receipt reviews",value:String(summary.reviewCount),note:`${summary.draftCount} drafts awaiting review`,to:"review"}].map(metric=><Link key={metric.label} href={href(metric.to as CollectionView)} className="min-w-0 border-b border-r border-border p-4 transition hover:bg-muted/50 sm:p-5 lg:border-b-0"><p className="text-xs font-semibold text-muted-foreground">{metric.label}</p><p className="mt-2 break-words text-2xl font-bold tabular-nums tracking-tight sm:text-3xl">{metric.value}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{metric.note}</p></Link>)}
    </section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
      <section aria-labelledby="invoice-register" className="min-w-0">
        <div className="flex flex-wrap items-center justify-between gap-2"><h2 id="invoice-register" className="text-lg font-semibold">Invoice register</h2><p className="text-xs text-muted-foreground">{visible.length} of {invoices.length} records</p></div>
        <form method="get" className="relative mt-4"><input type="hidden" name="view" value={view}/>{status&&<input type="hidden" name="status" value={status}/>}<Search size={17} aria-hidden="true" className="absolute left-3 top-3 text-muted-foreground"/><label htmlFor="invoice-search" className="sr-only">Search invoice, client or job</label><input id="invoice-search" name="q" defaultValue={q} maxLength={160} placeholder="Search invoice, client or job" className="h-11 w-full rounded-md border border-border bg-white pl-10 pr-24 text-sm"/><button className="absolute right-1 top-1 rounded px-3 py-2 text-xs font-semibold hover:bg-muted" type="submit">Search</button></form>
        <nav aria-label="Invoice filters" className="my-4 flex flex-wrap gap-2">{collectionViews.map(item=><Link key={item} href={href(item)} aria-current={item===view&&!status?"page":undefined} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${item===view&&!status?"border-foreground bg-foreground text-background":"border-border bg-white hover:bg-muted"}`}>{labels[item]}</Link>)}</nav>
        {status&&<p className="mb-3 text-sm">Saved status: {status.toLowerCase().replaceAll("_"," ")} · <Link className="text-primary underline" href={href(view)}>Clear status filter</Link></p>}
        {visible.length===0 ? <div className="border border-dashed border-border bg-white p-8 text-center"><h3 className="font-semibold">{invoices.length ? "No invoices match this view" : "Your invoice register is ready"}</h3><p className="mt-2 text-sm text-muted-foreground">{invoices.length ? "Choose another filter or clear the search." : "Create an invoice when the agreed payment milestone is ready."}</p><Link href={invoices.length?"/invoices":"/invoices/new"} className="mt-4 inline-block text-sm font-semibold text-primary underline">{invoices.length?"Show all invoices":"Create first invoice"}</Link></div> : <div className="divide-y divide-border border-y border-border bg-white">{visible.map(({invoice,state})=><article key={invoice.id} className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/invoices/${invoice.id}`} className="font-bold underline-offset-4 hover:underline">{invoice.invoiceNumber}</Link><StatusPill value={invoice.status}/></div><p className="mt-2 text-sm font-medium">{invoice.clientProfile?.profileName??"Client not assigned"}</p>{invoice.job&&<Link href={`/jobs/${invoice.job.id}`} className="mt-1 block text-xs text-muted-foreground hover:underline">{invoice.job.jobName}</Link>}</div><div className="text-right"><p className="text-xl font-semibold tabular-nums">{money(invoice.balanceDue)}</p><p className="text-xs text-muted-foreground">Recorded balance</p></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-border/60 pt-3"><div className="text-xs"><p className={state.overdue?"font-semibold text-destructive":"text-muted-foreground"}>{state.open?state.dueLabel:`Due ${dateShort(invoice.dueDate)}`}</p><p className="mt-1 text-muted-foreground">{state.needsReview?"Receipt review needed before collection":`${money(state.receipts)} in completed receipts`}</p></div><div className="flex flex-wrap items-center gap-4 text-xs font-semibold"><Link href={`/api/pdf/invoice/${invoice.id}`} className="text-muted-foreground hover:underline">PDF</Link><Link href={`/invoices/${invoice.id}${state.needsReview?"#receipt-review":""}`} className="inline-flex items-center gap-1 text-primary">{state.nextAction}<ArrowRight size={14} aria-hidden="true"/></Link></div></div></article>)}</div>}
      </section>
      <aside className="min-w-0 space-y-6">
        <section className="border-l-4 border-accent bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Next actions</h2><span className="text-xs text-muted-foreground">{summary.queue.length} items</span></div>{summary.queue.length ? <ol className="mt-2 divide-y divide-border">{summary.queue.slice(0,4).map(({invoice,state},index)=><li key={invoice.id} className="py-4"><Link href={`/invoices/${invoice.id}${state.needsReview?"#receipt-review":""}`} className="group flex gap-3"><span className="pt-0.5 text-xs font-bold text-muted-foreground">0{index+1}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold group-hover:underline">{state.nextAction}</span><span className="mt-1 block text-xs text-muted-foreground">{invoice.invoiceNumber} · {invoice.clientProfile?.profileName??"Unassigned client"}</span><span className="mt-1 block text-xs">{state.needsReview?"Recorded amounts need evidence review":invoice.status==="DRAFT"?"Confirm scope and payment milestone":state.dueLabel}</span></span><ArrowUpRight size={16} aria-hidden="true" className="shrink-0 text-muted-foreground"/></Link></li>)}</ol>:<p className="mt-3 text-sm text-muted-foreground">No due-date or receipt issues are flagged in these records.</p>}<Link href="/payments/reconciliation" className="mt-3 inline-block text-xs font-semibold text-primary underline">Open full reconciliation</Link></section>
        <section className="border border-border bg-white p-5"><h2 className="font-semibold">Balance aging</h2><p className="mt-1 text-xs text-muted-foreground">As of {dateShort(today)} · Austin</p><dl className="mt-4 space-y-3">{summary.aging.map(bucket=><div key={bucket.label} className="flex justify-between gap-2 text-sm"><dt className="text-muted-foreground">{bucket.label}<span className="ml-1 text-xs">({bucket.count})</span></dt><dd className="font-semibold tabular-nums">{money(bucket.amount)}</dd></div>)}</dl><p className="mt-4 border-t border-border pt-3 text-xs leading-relaxed text-muted-foreground">Recorded balances, not a cash forecast. Draft, paid and void invoices are excluded. Resolve flagged receipt differences before requesting payment.</p></section>
      </aside>
    </div>
  </div>;
}
